/*global systemDictionary:true */
"use strict";

systemDictionary = {
    "Extracted %s states": {                         "en": "Extracted %s states",                             "de": "Extrahierte %s-Zustände",                         "ru": "Извлечено% s состояний",                          "pt": "Estados% s extraídos",                            "nl": "Geëxtraheerde %s staten",                         "fr": "États %s extraits",                               "it": "%s stati estratti",                               "es": "Estados% s extraídos",                            "pl": "Wyodrębnione stany %s",                           "zh-cn": "提取 %s 状态"},
    "Frames per second": {                           "en": "Frames per second",                               "de": "Bilder pro Sekunde",                              "ru": "Кадров в секунду",                                "pt": "Quadros por segundo",                             "nl": "Beelden per seconde",                             "fr": "Images par seconde",                              "it": "Fotogrammi al secondo",                           "es": "Cuadros por segundo",                             "pl": "Klatki na sekundę",                               "zh-cn": "每秒帧数"},
    "Import XML from ETS": {                      "en": "Import XML from ETS",                          "de": "Import XML aus ETS",                           "ru": "Экспорт GA XML из ETS",                           "pt": "Exportação GA XML de ETS",                        "nl": "GA XML-export vanuit ETS",                        "fr": "Exportation XML GA depuis ETS",                   "it": "Esportazione XML GA da ETS",                      "es": "Exportación GA XML desde ETS",                    "pl": "Eksport XML GA z ETS",                            "zh-cn": "从 ETS 导出 GA XML"},
    "Gateway IP": {                                  "en": "Gateway IP",                                      "de": "Gateway-IP",                                      "ru": "IP шлюза",                                        "pt": "IP do gateway",                                   "nl": "Gateway IP",                                      "fr": "IP de la passerelle",                             "it": "IP gateway",                                      "es": "IP de acceso",                                    "pl": "IP bramy",                                        "zh-cn": "网关IP"},
    "How to export GA XML from ETS:": {              "en": "How to export GA XML from ETS:",                  "de": "So exportieren Sie GA-XML aus der ETS:",          "ru": "Как экспортировать GA XML из ETS:",               "pt": "Como exportar GA XML do ETS:",                    "nl": "GA XML exporteren vanuit ETS:",                   "fr": "Comment exporter GA XML depuis ETS :",            "it": "Come esportare GA XML da ETS:",                   "es": "Cómo exportar GA XML desde ETS:",                 "pl": "Jak wyeksportować GA XML z ETS:",                 "zh-cn": "如何从 ETS 导出 GA XML："},
    "KNXproj are not supported, please open in ETS the Group Adresses and right click on group addresses and then group adresse export": {"en": "KNXproj are not supported, please open in ETS the Group Adresses and right click on group addresses and then group adresse export", "de": "KNXproj werden nicht unterstützt, bitte öffnen Sie in der ETS die Gruppenadressen und klicken Sie mit der rechten Maustaste auf Gruppenadressen und dann Gruppenadressen-Export", "ru": "KNXproj не поддерживаются, откройте в ETS групповые адреса и щелкните правой кнопкой мыши по групповым адресам, а затем экспортируйте групповые адреса.", "pt": "KNXproj não são suportados, por favor, abra no ETS o Group Adresses e clique com o botão direito nos endereços de grupo e então a exportação de endereço de grupo", "nl": "KNXproj worden niet ondersteund, open in ETS de groepsadressen en klik met de rechtermuisknop op groepsadressen en exporteer groepsadressen", "fr": "KNXproj ne sont pas pris en charge, veuillez ouvrir dans ETS les adresses de groupe et faites un clic droit sur les adresses de groupe, puis exportez l'adresse de groupe", "it": "KNXproj non sono supportati, aprire in ETS gli indirizzi di gruppo e fare clic con il pulsante destro del mouse sugli indirizzi di gruppo e quindi esportare gli indirizzi di gruppo", "es": "KNXproj no es compatible, abra en ETS las direcciones del grupo y haga clic con el botón derecho en las direcciones del grupo y luego exportar la dirección del grupo.", "pl": "KNXproj nie są obsługiwane, otwórz w ETS adresy grup i kliknij prawym przyciskiem adresy grup, a następnie wyeksportuj adresy grup", "zh-cn": "不支持KNXproj，请在ETS中打开群组地址，右键点击群组地址，然后群组地址导出"},
    "Port": {                                        "en": "Port",                                            "de": "Hafen",                                           "ru": "Порт",                                            "pt": "Porta",                                           "nl": "Haven",                                           "fr": "Port",                                            "it": "Porta",                                           "es": "Puerto",                                          "pl": "Port",                                            "zh-cn": "港口"},
    "Regex to identify Status GAs (ending with status, rm, rückmeldung..).": {"en": "Regex to identify Status GAs (ending with status, rm, rückmeldung..)", "de": "Regex zum Erkennen von Status-GAs (Endung mit status, rm, rückmeldung..)", "ru": "Регулярное выражение для определения GA состояния (заканчивающееся на status, rm, rückmeldung ..). ", "pt": "Regex para identificar Status GAs (terminando com status, rm, rückmeldung ..). ", "nl": "Regex om Status GA's te identificeren (eindigend met status, rm, rückmeldung..). ", "fr": "Regex pour identifier les Status GA (se terminant par status, rm, rückmeldung..). ", "it": "Regex per identificare gli Status GA (che termina con status, rm, rückmeldung..). ", "es": "Regex para identificar estados GA (terminando con status, rm, rückmeldung ..). ", "pl": "Regex do identyfikacji statusów GA (kończących się na status, rm, rückmeldung...). ", "zh-cn": "用于识别状态 GA 的正则表达式（以状态、rm、rückmeldung 结尾...）。"},
    "Restarting adapter": {                          "en": "Restarting adapter...",                           "de": "Adapter neu starten...",                          "ru": "Перезапуск адаптера ...",                         "pt": "Reiniciando o adaptador ...",                     "nl": "Adapter opnieuw opstarten...",                    "fr": "Redémarrage de l'adaptateur...",                  "it": "Riavvio dell'adattatore...",                      "es": "Reiniciando el adaptador ...",                    "pl": "Ponowne uruchamianie adaptera...",                "zh-cn": "重新启动适配器..."},
    "Unsupported file format": {                     "en": "Unsupported file format",                         "de": "Nicht unterstütztes Dateiformat",                 "ru": "Неподдерживаемый формат файла",                   "pt": "Formato de arquivo não suportado",                "nl": "Niet ondersteund bestandsformaat",                "fr": "Format de fichier non pris en charge",            "it": "Formato file non supportato",                     "es": "Formato de archivo no soportado",                 "pl": "Niewspierany format pliku",                       "zh-cn": "不支持的文件格式"},
    "add only new Objects": {                        "en": "Add only new Objects",                            "de": "Nur neue Objekte hinzufügen",                     "ru": "Добавляйте только новые объекты",                 "pt": "Adicionar apenas novos objetos",                  "nl": "Alleen nieuwe objecten toevoegen",                "fr": "Ajouter uniquement de nouveaux objets",           "it": "Aggiungi solo nuovi oggetti",                     "es": "Agregar solo nuevos objetos",                     "pl": "Dodaj tylko nowe obiekty",                        "zh-cn": "仅添加新对象"},
    "invalid IP address": {                          "en": "invalid IP address",                              "de": "ungültige IP-Adresse",                            "ru": "неверный IP-адрес",                               "pt": "endereço IP inválido",                            "nl": "ongeldig IP-adres",                               "fr": "adresse IP invalide",                             "it": "indirizzo IP non valido",                         "es": "Dirección IP inválida",                           "pl": "nieprawidłowy adres IP",                          "zh-cn": "无效的 IP 地址"},
    "invalid port number": {                         "en": "invalid port number",                             "de": "ungültige Portnummer",                            "ru": "неверный номер порта",                            "pt": "número de porta inválido",                        "nl": "ongeldig poortnummer",                            "fr": "numéro de port invalide",                         "it": "numero di porta non valido",                      "es": "número de puerto no válido",                      "pl": "nieprawidłowy numer portu",                       "zh-cn": "无效的端口号"},
    "local network interface": {                     "en": "local network interface",                         "de": "lokale Netzwerkschnittstelle",                    "ru": "локальный сетевой интерфейс",                     "pt": "interface de rede local",                         "nl": "lokale netwerkinterface",                         "fr": "interface réseau local",                          "it": "interfaccia di rete locale",                      "es": "interfaz de red local",                           "pl": "lokalny interfejs sieciowy",                      "zh-cn": "本地网络接口"},
    "min 1": {                                       "en": "minimum is 1",                                    "de": "Minimum ist 1",                                   "ru": "минимум 1",                                       "pt": "mínimo é 1",                                      "nl": "minimum is 1",                                    "fr": "le minimum est 1",                                "it": "il minimo è 1",                                   "es": "el mínimo es 1",                                  "pl": "minimum to 1",                                    "zh-cn": "最小值为 1"},
    "override object path": {                        "ru": "переопределить путь к объекту",                   "pt": "substituir o caminho do objeto",                  "nl": "objectpad overschrijven",                         "fr": "remplacer le chemin de l'objet",                  "it": "sovrascrivere il percorso dell'oggetto",          "es": "anular la ruta del objeto",                       "pl": "nadpisz ścieżkę obiektu",                         "zh-cn": "覆盖对象路径"},
    "physical KNX address": {                        "en": "physical KNX address",                            "de": "physikalische KNX-Adresse",                       "ru": "физический адрес KNX",                            "pt": "endereço KNX físico",                             "nl": "fysiek KNX-adres",                                "fr": "adresse physique KNX",                            "it": "indirizzo fisico KNX",                            "es": "dirección KNX física",                            "pl": "fizyczny adres KNX",                              "zh-cn": "物理 KNX 地址"},
    "physical KNX address in format a/b/c not valid": {"en": "physical KNX address in format a/b/c not valid",  "de": "physikalische KNX-Adresse im Format a/b/c ungültig", "ru": "физический адрес KNX в формате a / b / c недействителен", "pt": "endereço KNX físico em formato a / b / c inválido", "nl": "fysiek KNX-adres in formaat a/b/c niet geldig",   "fr": "adresse physique KNX au format a/b/c non valide", "it": "indirizzo fisico KNX in formato a/b/c non valido", "es": "dirección KNX física en formato a / b / c no válida", "pl": "fizyczny adres KNX w formacie a/b/c nieważny",    "zh-cn": "格式为 a/b/c 的物理 KNX 地址无效"},
    "this is not a number": {                        "en": "this is not a number",                            "de": "das ist keine Zahl",                              "ru": "это не число",                                    "pt": "este não é um número",                            "nl": "dit is geen nummer",                              "fr": "ce n'est pas un nombre",                          "it": "questo non è un numero",                          "es": "esto no es un numero",                            "pl": "to nie jest liczba",                              "zh-cn": "这不是一个数字"},
    "using old knx path for objects": {              "ru": "использование старого пути knx для объектов",     "pt": "usando o caminho antigo do knx para objetos",     "nl": "oud knx-pad gebruiken voor objecten",             "fr": "utiliser l'ancien chemin knx pour les objets",    "it": "usando il vecchio percorso knx per gli oggetti",  "es": "usando la vieja ruta knx para objetos",           "pl": "używając starej ścieżki knx dla obiektów",        "zh-cn": "对对象使用旧的 knx 路径"},
    "using old knx path for objects (Before importing, delete old objects manually)": {"ru": "использование старого пути knx для объектов (перед импортом удалите старые объекты вручную)", "pt": "usando o caminho antigo do knx para objetos (antes de importar, exclua os objetos antigos manualmente)", "nl": "het oude knx-pad voor objecten gebruiken (verwijder oude objecten handmatig voordat u ze importeert)", "fr": "en utilisant l'ancien chemin knx pour les objets (Avant d'importer, supprimez les anciens objets manuellement)", "it": "utilizzando il vecchio percorso knx per gli oggetti (prima dell'importazione, elimina manualmente i vecchi oggetti)", "es": "utilizando la ruta de knx antigua para los objetos (antes de importar, elimine los objetos antiguos manualmente)", "pl": "używanie starej ścieżki knx dla obiektów (Przed importem usuń ręcznie stare obiekty)", "zh-cn": "使用对象的旧 knx 路径（导入前，手动删除旧对象）"},
    "Minimum Similarity 0-1": {
        "en": "Minimum Similarity 0-1",
        "de": "Mindest Ähnlichkeit 0-1",
        "ru": "Минимальное сходство 0-1",
        "pt": "Similaridade mínima 0-1",
        "nl": "Minimale gelijkenis 0-1",
        "fr": "Similitude minimale 0-1",
        "it": "Somiglianza minima 0-1",
        "es": "Similitud mínima 0-1",
        "pl": "Minimalne podobieństwo 0-1",
        "zh-cn": "最小相似度 0-1"
    },
    "Alias path": {
        "en": "Alias path",
        "de": "Alias-Pfad",
        "ru": "Путь псевдонима",
        "pt": "Caminho de alias",
        "nl": "Aliaspad",
        "fr": "Chemin d'alias",
        "it": "Alias percorso",
        "es": "Ruta de alias",
        "pl": "Ścieżka aliasu",
        "zh-cn": "别名路径"
    },
    "generate aliases": {
        "en": "generate aliases",
        "de": "Aliase generieren",
        "ru": "генерировать псевдонимы",
        "pt": "gerar apelidos",
        "nl": "aliassen genereren",
        "fr": "générer des alias",
        "it": "generare alias",
        "es": "generar alias",
        "pl": "generować aliasy",
        "zh-cn": "生成别名"
    },
    "To merge Action and Status GA in one ioBroker Object you can let the Adapter generate": {
        "en": "To merge Action and Status GA in one ioBroker Object you can let the Adapter generate",
        "de": "Um Aktor und Zustand GA in einem ioBroker-Objekt zusammenzuführen, können Sie den Adapter Aliase generieren lassen.",
        "ru": "Чтобы объединить Action и Status GA в один объект ioBroker, вы можете позволить адаптеру сгенерировать",
        "pt": "Para mesclar Action e Status GA em um objeto ioBroker, você pode deixar o adaptador gerar",
        "nl": "Om Action en Status GA in één ioBroker-object samen te voegen, kunt u de Adapter laten genereren:",
        "fr": "Pour fusionner l'action et le statut GA dans un seul objet ioBroker, vous pouvez laisser l'adaptateur générer",
        "it": "Per unire Action e Status GA in un oggetto ioBroker puoi lasciare che l'adattatore generi",
        "es": "Para fusionar Acción y Estado GA en un Objeto ioBroker, puede dejar que el Adaptador genere",
        "pl": "Aby połączyć działanie i status GA w jednym obiekcie ioBroker, możesz pozwolić adapterowi na generowanie",
        "zh-cn": "要将 Action 和 Status GA 合并到一个 ioBroker 对象中，您可以让适配器生成"
    },
    "Click here for a manual to migrate from knx.0 to openknx.0": {
        "en": "Click here for a manual to migrate from knx.0 to openknx.0",
        "de": "Klicken Sie hier für eine Anleitung zur Migration von knx.0 zu openknx.0",
        "ru": "Щелкните здесь, чтобы получить руководство по переходу с knx.0 на openknx.0",
        "pt": "Clique aqui para obter um manual para migrar de knx.0 para openknx.0",
        "nl": "Klik hier voor een handleiding om te migreren van knx.0 naar openknx.0",
        "fr": "Cliquez ici pour un manuel de migration de knx.0 vers openknx.0",
        "it": "Fare clic qui per un manuale per migrare da knx.0 a openknx.0",
        "es": "Haga clic aquí para obtener un manual para migrar de knx.0 a openknx.0",
        "pl": "Kliknij tutaj, aby uzyskać instrukcję migracji z knx.0 do openknx.0",
        "zh-cn": "单击此处获取从 knx.0 迁移到 openknx.0 的手册"
    },
    "DEPRECATED! Connecting Action and Status GA directly like the knx adapter": {
        "en": "DEPRECATED! Connecting Action and Status GA directly like the knx adapter",
        "de": "VERALTET! Action und Status GA direkt verbinden wie der knx-Adapter",
        "ru": "УСТАРЕЛО! Подключение Action и Status GA напрямую, как адаптер knx",
        "pt": "DESCONTINUADA! Conectando Action e Status GA diretamente como o adaptador knx",
        "nl": "VEROUDERD! Actie en Status GA rechtstreeks verbinden zoals de knx-adapter",
        "fr": "DÉCONSEILLÉ ! Connecter Action et Status GA directement comme l'adaptateur knx",
        "it": "DEPRECATO! Collegamento di Action e Status GA direttamente come l'adattatore knx",
        "es": "¡OBSOLETO! Conectando Action y Status GA directamente como el adaptador knx",
        "pl": "PRZESTARZAŁE! Podłączanie akcji i statusu GA bezpośrednio jak adapter knx",
        "zh-cn": "已弃用！像 knx 适配器一样直接连接 Action 和 Status GA"
    },
    "generate connections": {
        "en": "generate connections",
        "de": "Verbindungen herstellen",
        "ru": "генерировать связи",
        "pt": "gerar conexões",
        "nl": "verbindingen genereren",
        "fr": "générer des connexions",
        "it": "generare connessioni",
        "es": "generar conexiones",
        "pl": "generuj połączenia",
        "zh-cn": "产生连接"
    },
    "This is deprecated. Please rethink to use Aliases. This will not supported in the future.": {
        "en": "This is deprecated. Please rethink to use Aliases. This will not more supported in the future.",
        "de": "Dies ist veraltet. Bitte überdenken Sie die Verwendung von Aliasen. Dieses Feature wird offiziell nicht unterstützt.",
        "ru": "Это устарело. Пожалуйста, подумайте еще раз, чтобы использовать псевдонимы. Это больше не будет поддерживаться в будущем.",
        "pt": "Isso está obsoleto. Por favor, repense para usar aliases. Isso não terá mais suporte no futuro.",
        "nl": "Dit wordt afgeraden. Denk er nog eens over na om aliassen te gebruiken. Dit zal in de toekomst niet meer ondersteund worden.",
        "fr": "Ceci est obsolète. Veuillez repenser l'utilisation des alias. Cela ne sera plus pris en charge à l'avenir.",
        "it": "Questo è deprecato. Si prega di ripensare all'uso degli alias. Questo non sarà più supportato in futuro.",
        "es": "Esto está desaprobado. Por favor, reconsidere el uso de alias. Esto no tendrá más apoyo en el futuro.",
        "pl": "To jest przestarzałe. Proszę przemyśleć użycie aliasów. To nie będzie więcej obsługiwane w przyszłości.",
        "zh-cn": "这已被弃用。请重新考虑使用别名。将来不会更多地支持这一点。"
    },
    "Deprecated": {
        "en": "Deprecated",
        "de": "Veraltet",
        "ru": "Устарело",
        "pt": "Descontinuada",
        "nl": "Verouderd",
        "fr": "Obsolète",
        "it": "Deprecato",
        "es": "Obsoleto",
        "pl": "Przestarzałe",
        "zh-cn": "已弃用"
    },
    "Generated %s connections": {
        "en": "Generated %s connections",
        "de": "%s Verbindungen generiert",
        "ru": "Создано %s  подключений",
        "pt": "% S conexões geradas",
        "nl": "%s verbindingen gegenereerd",
        "fr": "%s connexions générées",
        "it": "%s connessioni generate",
        "es": "Conexiones %s  generadas",
        "pl": "Wygenerowano %s połączeń",
        "zh-cn": "生成了 %s 个连接"
    },
    "Alias Generation": {
        "en": "Alias Generation",
        "de": "Alias Generierung",
        "ru": "Генерация псевдонима",
        "pt": "Geração de Alias",
        "nl": "Alias Generatie",
        "fr": "Génération d'alias",
        "it": "Generazione alias",
        "es": "Generación de alias",
        "pl": "Generowanie aliasów",
        "zh-cn": "别名生成"
    },
    "Settings and Import": {
        "en": "Settings and Import",
        "de": "Einstellungen und Import",
        "ru": "Настройки и импорт",
        "pt": "Configurações e importação",
        "nl": "Instellingen en importeren",
        "fr": "Paramètres et importation",
        "it": "Impostazioni e importazione",
        "es": "Configuración e importación",
        "pl": "Ustawienia i import",
        "zh-cn": "设置和导入"
    },
    "To find Action and Status GA pairs we assume the name is similar only status or rückmeldung is added": {
        "en": "To find Action and Status GA pairs we assume the name is similar only status or rückmeldung is added",
        "de": "Um Action- und Status-GA-Paare zu finden, gehen wir davon aus, dass der Name ähnlich ist, nur die Endung Status oder Rückmeldung hat",
        "ru": "Чтобы найти пары Action и Status GA, мы предполагаем, что имя похоже, только добавлен статус или rückmeldung",
        "pt": "Para encontrar pares de ação e status GA, presumimos que o nome é semelhante, apenas status ou rückmeldung é adicionado",
        "nl": "Om Action en Status GA-paren te vinden, nemen we aan dat de naam vergelijkbaar is, alleen status of rückmeldung is toegevoegd",
        "fr": "Pour trouver les paires Action et Statut GA, nous supposons que le nom est similaire, seul le statut ou rückmeldung est ajouté",
        "it": "Per trovare le coppie Action e Status GA, supponiamo che il nome sia simile solo lo stato o viene aggiunto rückmeldung",
        "es": "Para encontrar pares de acción y estado, asumimos que el nombre es similar solo estado o se agrega rückmeldung",
        "pl": "Aby znaleźć pary akcji i statusu GA, zakładamy, że nazwa jest podobna, dodawany jest tylko status lub rückmeldung",
        "zh-cn": "为了找到 Action 和 Status GA 对，我们假设名称相似，只是添加了 status 或 rückmeldung"
    }

};